export { HeroSection } from './hero-section'
export { SkillsSection } from './skills-section'
export { ExperienceSection } from './experience-section'
export { EducationSection } from './education-section'
export { ProjectsSection } from './projects-section'
export { AdditionalInfoSection } from './additional-info-section'
export { ContactsSection } from './contacts-section'